export const FEAT_ATTRIBUTE_OPTIONS = [
  "Fuerza",
  "Destreza",
  "Constitucion",
  "Inteligencia",
  "Sabiduria",
  "Carisma",
];

export const WEAPON_MASTER_OPTIONS = [
  "Garrote",
  "Daga",
  "Gran garrote",
  "Hacha de mano",
  "Dardo",
  "Jabalina",
  "Honda",
  "Bastón",
  "Hoz",
  "Lanza",
  "Ballesta ligera",
  "Arco corto",
  "Cerbatana",
  "Gran hacha",
  "Hacha de batalla",
  "Guja",
  "Mandoble",
  "Alabarda",
  "Lanza de caballería",
  "Gran maza",
  "Lucero del alba",
  "Cimitarra",
  "Espada corta",
  "Espada larga",
  "Ballesta de mano",
  "Ballesta pesada",
  "Estoque",
  "Arco largo",
  "Hacha de guerra",
  "Martillo de guerra",
  "Mangual",
  "Pica",
  "Tridente",
  "Látigo",
  "Pico de guerra",
  "Red",
];

export const FEAT_LANGUAGE_OPTIONS = [
  "Abisal",
  "Celestial",
  "Comun",
  "Draconico",
  "Enano",
  "Elfico",
  "Gigante",
  "Gnomo",
  "Goblin",
  "Halfling (Mediano)",
  "Infernal",
  "Orco",
  "Primordial",
  "Silvano",
  "Infracomun",
];

export const FEAT_SKILL_OPTIONS = [
  "Acrobacias",
  "Arcano",
  "Atletismo",
  "Engano",
  "Historia",
  "Investigacion",
  "Interpretacion",
  "Intimidacion",
  "Juego de manos",
  "Medicina",
  "Naturaleza",
  "Percepcion",
  "Perspicacia",
  "Persuasion",
  "Sigilo",
  "Supervivencia",
  "Trato con Animales",
];

export const MAGIC_INITIATE_CLASS_OPTIONS = [
  "bardo",
  "brujo",
  "clerigo",
  "druida",
  "hechicero",
  "mago",
];
