spring:
  application:
    name: fosteriaVTT-backend

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

app:
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
  jwt:
    secret: ${JWT_SECRET:}
    expiration: ${JWT_EXPIRATION:}

server:
  port: ${PORT:8080}
